import { JSDOM } from "jsdom"; import fs from "fs";
const src = fs.readFileSync(new URL("../hotbar.js", import.meta.url), "utf8");
const dom=new JSDOM("<!doctype html><html><body></body></html>",{url:"https://claude.ai/",runScripts:"outside-only"});
const w=dom.window; const NOW=Date.now();
w.Notification=function(){};w.Notification.permission="granted";w.Notification.requestPermission=()=>{};
w.setInterval=()=>1;w.clearInterval=()=>{};
w.localStorage.setItem("epitaxy-unread-v1",JSON.stringify({state:{unreadIds:[]},version:0}));
const sessions=[]; for(let i=0;i<34;i++) sessions.push({sessionId:"s"+i,title:"Session "+i,isRunning:false,isArchived:false,lastActivityAt:NOW-i*100000});
w["claude.web"]={LocalSessions:{getAll(){return w.Promise.resolve(sessions);},onOnEvent(){return()=>{};},setFocusedSession(){},getTranscript(){return w.Promise.resolve([]);}}};
w.eval(src);
await new w.Promise(r=>setTimeout(r,40));
const bar=w.document.getElementById("claude-hotbar");
const fail=[]; const ok=(c,m)=>{if(!c)fail.push(m);};
bar.querySelector(".hb-toggle").dispatchEvent(new w.MouseEvent("click",{bubbles:true}));
await new w.Promise(r=>setTimeout(r,20));
const panel=bar.querySelector(".hb-panel");
const scroll=bar.querySelector(".hb-scroll");
const searchDirectChild = panel && [...panel.children].some(c=>c.className==="hb-search");
const searchInScroll = scroll && scroll.querySelector(".hb-search");
const rowsInScroll = scroll ? scroll.querySelectorAll(".hb-row").length : 0;
const rowsOutsideScroll = panel ? [...panel.children].filter(c=>c.className==="hb-row").length : 0;
const recentHdr=[...bar.querySelectorAll(".hb-grp")].map(g=>g.textContent).find(t=>/Recent/.test(t));
console.log(JSON.stringify({searchDirectChild,searchInScroll:!!searchInScroll,rowsInScroll,rowsOutsideScroll,recentHdr},null,1));
ok(!!scroll,"inner .hb-scroll container exists");
ok(searchDirectChild,"search is a direct child of panel (fixed header)");
ok(!searchInScroll,"search is NOT inside the scroll region (won't scroll away)");
ok(rowsInScroll>=34,"all rows live inside .hb-scroll (got "+rowsInScroll+")");
ok(rowsOutsideScroll===0,"no rows leak outside the scroll region");
ok(/Recent . showing 34 of 34/.test(recentHdr),"recent shows full count: "+recentHdr);
console.log("\n"+(fail.length?"FAIL:\n - "+fail.join("\n - "):"PANEL SCROLL-CONTAINER CHECK PASSED"));
process.exit(fail.length?1:0);
